/** **What looks odd, and the rule that thought so.**
 *
 * Every detector here is a claim about a SHAPE in the tape, never about
 * intent. A refusal storm is somebody being refused a lot — it is not an
 * attack; a pair trading back and forth is a shape the model says earns
 * nothing — it is not a wash trade; a community settling in cash is not a
 * verdict on the ledger. So each carries its rule in its own words, and the
 * reader decides what it was.
 *
 * Nothing here is a measurement of how people behave: every act on a tape
 * was generated by a model playing somebody, and a pattern in one run is a
 * fact about that run.
 */

const money = (minor) => (minor / 100).toFixed(2);
const party = (p) => (p && typeof p === "object" ? (p.member ?? null) : null);

/** Every act on the tape up to a day, with who did it and whether it was
 *  refused before it was ever applied. */
function allActs(days, upto) {
  const out = [];
  for (let i = 0; i <= upto && i < days.length; i++) {
    const day = days[i];
    for (const e of day.events || []) {
      if (e.event === "day") {
        for (const a of e.acts || []) out.push({ ...a, person: e.person, at: i, epoch: day.epoch, refused: false });
        for (const a of e.refused || []) out.push({ ...a, person: e.person, at: i, epoch: day.epoch, refused: true });
      }
      if (e.event === "instructions")
        for (const a of e.fired || [])
          out.push({
            ...a,
            at: i,
            epoch: day.epoch,
            // A fired act carries its result inline rather than in a `refused`
            // list. Taking it as kept counted refusals as acts.
            refused: !!(a.result && ["refused", "rejected"].includes(a.result.result)),
            standing: true,
          });
    }
  }
  return out;
}

/** Every change a contract went through, day by day. */
function contractChanges(days, upto) {
  const prev = new Map();
  const out = [];
  for (let i = 0; i <= upto && i < days.length; i++)
    for (const c of days[i].contracts) {
      const earlier = prev.get(c.id);
      if (earlier) out.push({ was: earlier, now: c, at: i, epoch: days[i].epoch });
      prev.set(c.id, c);
    }
  return out;
}

const hit = (at, epoch, people, detail) => ({ at, epoch, people: people.filter((p) => p != null), detail });
const personOf = (day, id) => day.members.find((m) => m.id === id)?.person ?? null;

export function anomalies(days, upto) {
  const acts = allActs(days, upto);
  const changes = contractChanges(days, upto);
  const day = days[Math.max(0, Math.min(upto, days.length - 1))];
  if (!day) return [];
  const kept = acts.filter((a) => !a.refused);
  const refused = acts.filter((a) => a.refused);
  const of = (name) => kept.filter((a) => a.act && a.act.act === name);

  // ---- the ledger's own verdicts ----------------------------------------
  const violations = [];
  for (let i = 0; i <= upto && i < days.length; i++)
    for (const e of days[i].events || [])
      if (e.event === "violation")
        violations.push(hit(i, days[i].epoch, [e.person], `${e.invariant} — ${e.act}`));

  const storms = (() => {
    const by = new Map();
    for (const a of refused) {
      // Only the ledger's codes: a world rejection is a sentence, and five of
      // them is not "refused five times with the same code".
      const code = a.result && a.result.code;
      if (!code) continue;
      const key = `${a.person}:${code}`;
      const seen = by.get(key) || { person: a.person, code, n: 0, first: a, last: a };
      seen.n += 1;
      seen.last = a;
      by.set(key, seen);
    }
    return [...by.values()]
      .filter((x) => x.n >= 5)
      .sort((a, b) => b.n - a.n)
      .map((x) => hit(x.last.at, x.last.epoch, [x.person], `refused ${x.n}× with ${x.code}, days ${x.first.epoch}–${x.last.epoch}`));
  })();

  const shutOut = (() => {
    const byDay = new Map();
    for (const a of acts) {
      const key = `${a.person}:${a.at}`;
      const seen = byDay.get(key) || { person: a.person, at: a.at, epoch: a.epoch, kept: 0, refused: 0 };
      if (a.refused) seen.refused += 1;
      else seen.kept += 1;
      byDay.set(key, seen);
    }
    return [...byDay.values()]
      .filter((d) => d.refused >= 2 && d.kept === 0)
      .map((d) => hit(d.at, d.epoch, [d.person], `every one of ${d.refused} acts refused; the day produced nothing`));
  })();

  const limitBound = (() => {
    const bond = refused.filter((a) => a.result && a.result.code === "ET-BND-001").length;
    if (bond < 10 || bond / Math.max(refused.length, 1) <= 0.5) return [];
    return [hit(upto, day.epoch, [], `${bond} of ${refused.length} refusals are ET-BND-001: the bond, not judgement, is what stopped people`)];
  })();

  // ---- credit and failure ------------------------------------------------
  const defaults = changes
    .filter((c) => c.was.status !== "expired" && c.now.status === "expired" && c.now.outstanding > 0)
    .map((c) => hit(c.at, c.epoch, [personOf(days[c.at], c.now.debtor), personOf(days[c.at], c.now.creditor)],
      `contract #${c.now.id}, ${money(c.now.outstanding)} outstanding, past its maturity`));

  const cures = changes
    .filter((c) => c.was.status === "expired" && ["settled", "cured"].includes(c.now.status))
    .map((c) => hit(c.at, c.epoch, [personOf(days[c.at], c.now.debtor)], `contract #${c.now.id} was cured after defaulting`));

  // **A transfer does not edit a row's debtor.** `move_debtor` closes the
  // contract (`status = transferred`, outstanding 0) and opens a NEW contract
  // for the successor, so a diff on `debtor` never fires — this study watched
  // for something the kernel cannot write. What it watches now is the row
  // closing, and the successor found by its amount and its original creditor.
  const handedOn = changes
    .filter((c) => c.was.status !== "transferred" && c.now.status === "transferred")
    .map((c) => {
      const after = (days[c.at].contracts || []).find(
        (x) => x.id !== c.now.id && x.creditor === c.now.creditor && x.original === c.now.original && x.status === "active",
      );
      return hit(
        c.at,
        c.epoch,
        [personOf(days[c.at], c.was.debtor), after ? personOf(days[c.at], after.debtor) : null],
        after
          ? `contract #${c.now.id} was taken over as #${after.id}: ${money(c.was.outstanding)} now owed by somebody else`
          : `contract #${c.now.id} moved to another debtor, ${money(c.was.outstanding)} outstanding`,
      );
    });

  const substitution = changes
    .filter((c) => c.was.creditor !== c.now.creditor)
    .map((c) => hit(c.at, c.epoch, [personOf(days[c.at], c.was.creditor), personOf(days[c.at], c.now.creditor)],
      `contract #${c.now.id} passed from one creditor to another — what an insured default does`));

  const lostInsurance = changes
    .filter((c) => c.was.insured && !c.now.insured && c.now.status !== "transferred" && c.now.outstanding > 0)
    .map((c) => hit(c.at, c.epoch, [personOf(days[c.at], c.now.creditor)],
      `contract #${c.now.id} stopped being insured: the creditor carries it alone now`));

  const concentration = (() => {
    const live = day.contracts.filter((c) => c.status === "active" || c.status === "expired");
    const total = live.reduce((s, c) => s + c.outstanding, 0);
    // One creditor holding 100% of one contract is not a concentration.
    if (!total || live.length < 5) return [];
    const by = new Map();
    for (const c of live) by.set(c.creditor, (by.get(c.creditor) || 0) + c.outstanding);
    return [...by]
      .filter(([, owed]) => owed / total > 0.4)
      .map(([id, owed]) => hit(upto, day.epoch, [personOf(day, id)], `owed ${money(owed)}, ${((owed / total) * 100).toFixed(0)}% of everything outstanding`));
  })();

  const maturityWall = (() => {
    const live = day.contracts.filter((c) => c.status === "active");
    const total = live.reduce((s, c) => s + c.outstanding, 0);
    const soon = live
      .filter((c) => c.maturity_epoch >= day.epoch && c.maturity_epoch - day.epoch <= 7)
      .reduce((s, c) => s + c.outstanding, 0);
    if (!total || soon / total < 0.4) return [];
    return [hit(upto, day.epoch, [], `${money(soon)} of ${money(total)} falls due within a week`)];
  })();

  const overExtended = day.members
    // `supply` is what this member underwrites for OTHERS; it says nothing
    // about what backs them. Excluding them dropped the largest debts in the
    // pilot — the founders — from a study about debt with nothing behind it.
    .filter((m) => m.debt > 0 && m.capacity === 0)
    .map((m) => hit(upto, day.epoch, [m.person], `owes ${money(m.debt)} with no capacity left to be insured for`));

  // ---- shapes worth a second look ---------------------------------------
  const bothWays = (() => {
    const pairs = new Map();
    for (const c of day.contracts.filter((c) => ["active", "expired"].includes(c.status))) {
      const key = `${Math.min(c.debtor, c.creditor)}:${Math.max(c.debtor, c.creditor)}`;
      const seen = pairs.get(key) || { a: Math.min(c.debtor, c.creditor), b: Math.max(c.debtor, c.creditor), ab: 0, ba: 0, n: 0 };
      seen.n += 1;
      if (c.debtor === seen.a) seen.ab += 1;
      else seen.ba += 1;
      pairs.set(key, seen);
    }
    return [...pairs.values()]
      .filter((p) => p.ab >= 2 && p.ba >= 2)
      .map((p) => hit(upto, day.epoch, [personOf(day, p.a), personOf(day, p.b)],
        `${p.n} contracts between the same two, ${p.ab} one way and ${p.ba} the other`));
  })();

  const roundAndSmall = (() => {
    const by = new Map();
    for (const a of of("offer")) {
      const amount = a.act.ask?.amount_minor;
      if (!amount || amount >= 5000 || amount % 1000 !== 0) continue;
      // An ask is a tagged union: only a SALE has a buyer and a seller. Reading
      // those two fields alone put every lend, settle and cure into one bucket
      // keyed on `null`, where three offers to three different people read as
      // three offers to the same one.
      const ask = a.act.ask;
      const other = [ask.buyer, ask.seller, ask.creditor, ask.debtor]
        .map(party)
        .find((p) => p != null && p !== a.person);
      if (other == null) continue;
      const key = `${a.person}:${other}`;
      const seen = by.get(key) || { person: a.person, other, n: 0, last: a };
      seen.n += 1;
      seen.last = a;
      by.set(key, seen);
    }
    return [...by.values()]
      .filter((x) => x.n >= 3)
      .map((x) => hit(x.last.at, x.last.epoch, [x.person], `${x.n} offers of round amounts under 50.00 to the same person`));
  })();

  const solicited = (() => {
    const out = [];
    const seen = new Set();
    // Hoisted: this was `of("offer")` INSIDE the loop, which made the whole
    // page quadratic in the length of the tape — 40 ms of a 200-day scrub step
    // on its own, and 14× that on a tape where people talk about records.
    const offers = of("offer");
    const said = of("message")
      .concat(of("post"))
      .sort((a, b) => a.at - b.at);
    for (const m of said) {
      const text = (m.act.text || "").toLowerCase();
      if (!/document|record|paperwork|invoice|favour|favor|help me|arrange/.test(text)) continue;
      // One hit per person per day: somebody who says the same thing in a post
      // and a message has not done it twice.
      const key = `${m.person}:${m.at}`;
      if (seen.has(key)) continue;
      seen.add(key);
      const after = offers.filter((o) => o.person === m.person && o.at >= m.at && o.at < m.at + 3);
      if (after.length)
        out.push(hit(m.at, m.epoch, [m.person], `wrote about records or arrangements, then made ${after.length} offer${after.length === 1 ? "" : "s"} within three days`));
    }
    return out;
  })();

  const seater = (() => {
    const by = new Map();
    for (const a of kept) {
      const seated = a.result && a.result.seated;
      if (!seated || !seated.length) continue;
      by.set(a.person, (by.get(a.person) || 0) + seated.length);
    }
    return [...by]
      .filter(([, n]) => n >= 3)
      .map(([person, n]) => hit(upto, day.epoch, [person], `brought ${n} new rows onto the ledger`));
  })();

  const pressed = (() => {
    const by = new Map();
    for (const d of of("decline")) {
      const key = `${d.person}`;
      by.set(key, (by.get(key) || 0) + 1);
    }
    return [...by]
      .filter(([, n]) => n >= 5)
      .map(([person, n]) => hit(upto, day.epoch, [Number(person)], `turned down ${n} offers`));
  })();

  const onlyBorrows = (() => {
    const owed = new Map();
    const owing = new Map();
    // A settled contract is not a position: "debtor on three and creditor on
    // none" was firing on three debts already repaid.
    for (const c of day.contracts.filter((c) => ["active", "expired"].includes(c.status))) {
      owing.set(c.debtor, (owing.get(c.debtor) || 0) + 1);
      owed.set(c.creditor, (owed.get(c.creditor) || 0) + 1);
    }
    return [...owing]
      .filter(([id, n]) => n >= 3 && !owed.has(id))
      .map(([id, n]) => hit(upto, day.epoch, [personOf(day, id)], `debtor on ${n} contracts and creditor on none`));
  })();

  // ---- adoption and behaviour -------------------------------------------
  const untouched = (() => {
    const traded = new Set();
    for (const c of day.contracts) {
      traded.add(c.debtor);
      traded.add(c.creditor);
    }
    const idle = day.members.filter((m) => !traded.has(m.id));
    // On day one nobody has been party to a contract, which is not a finding.
    return idle.length && day.contracts.length >= 3
      ? [hit(upto, day.epoch, idle.map((m) => m.person), `${idle.length} member${idle.length === 1 ? " has" : "s have"} never been party to a contract`)]
      : [];
  })();

  const settlingInCash = (() => {
    const cash = of("pay_cash").length;
    const ledger = of("offer").length + of("sign").length;
    if (!ledger || cash <= ledger) return [];
    return [hit(upto, day.epoch, [], `${cash} cash payments against ${ledger} acts on the ledger`)];
  })();

  const neverRefuses = (() => {
    // Every signature ATTEMPTED, not only the ones the ledger took: on the
    // pilot the bond refused 130 of 139 acts, and counting only what was kept
    // would have read a throttled community as one that accepts everything.
    const signs = acts.filter((a) => a.act && a.act.act === "sign").length;
    const declines = acts.filter((a) => a.act && a.act.act === "decline").length;
    if (signs < 10) return [];
    const rate = declines / (signs + declines);
    return rate >= 0.05
      ? []
      : [hit(upto, day.epoch, [], `${declines} declines against ${signs} signatures put to somebody — ${(rate * 100).toFixed(1)}% turned down`)];
  })();

  const silentPeople = (() => {
    // Trying and being refused is not doing nothing — the same page reports
    // those people under "a day where nothing got through".
    const acted = new Set(acts.map((a) => a.person));
    const known = new Set(days.slice(0, upto + 1).flatMap((d) => d.members.map((m) => m.person)));
    const quiet = [...known].filter((p) => p != null && !acted.has(p));
    return quiet.length ? [hit(upto, day.epoch, quiet, `${quiet.length} of the people here have done nothing at all`)] : [];
  })();

  const lostDays = (() => {
    const by = new Map();
    for (let i = 0; i <= upto && i < days.length; i++)
      for (const e of days[i].events || [])
        if (e.event === "silent") {
          const why = /rate limit/i.test(e.reason) ? "a rate limit" : /context/i.test(e.reason) ? "a life too long" : "a failed call";
          by.set(why, (by.get(why) || 0) + 1);
        }
    return [...by].map(([why, n]) =>
      hit(upto, day.epoch, [], `${n} person-day${n === 1 ? "" : "s"} lost to ${why} — the apparatus, not the people`),
    );
  })();

  // ---- the world ---------------------------------------------------------
  const underWater = (day.purses || [])
    .filter((p) => p.cash === 0 && p.arrears > 0)
    .map((p) => hit(upto, day.epoch, [p.person], `no cash and ${money(p.arrears)} of bills unpaid`));

  const pressure = (() => {
    const cut = day.economy.published.households_with_income_cut;
    const households = day.economy.published.households;
    if (!cut || !households || cut / households < 0.25) return [];
    const who = (day.purses || []).filter((p) => p.income_cut).map((p) => p.person);
    return [hit(upto, day.epoch, who, `${cut} of ${households} households are under an income cut`)];
  })();

  const crisis = (() => {
    const first = days.slice(0, upto + 1).findIndex((d) => d.economy.regime === "crisis");
    return first < 0 ? [] : [hit(first, days[first].epoch, [], `the economy first entered crisis on day ${days[first].epoch}${day.economy.regime === "crisis" ? " and is in it now" : ""}`)];
  })();

  return [
    {
      topic: "What the ledger itself refused",
      note: "The rules answering. These are the ledger's own words, not a reading of anybody's behaviour.",
      studies: [
        { title: "An invariant failed", weight: "grave", hits: violations, rule: "The ledger's audit refused a state it had reached. The one thing on this page that is not a hint: it ends the run." },
        { title: "Refused again and again", weight: "watch", hits: storms, rule: "One person refused five or more times with the same ledger code — a limit they keep meeting, a misunderstanding, or somebody trying doors." },
        { title: "A day where nothing got through", weight: "watch", hits: shutOut, rule: "Somebody acted and every act was refused, so the day produced nothing at all." },
        { title: "The activity limit, not judgement", weight: "note", hits: limitBound, rule: "More than half of all refusals — at least ten of them — are the operation bond. What stopped the community was its write budget rather than anybody's decision." },
      ],
    },
    {
      topic: "Credit, and how it failed",
      note: "What happened to obligations once they existed.",
      studies: [
        { title: "Contracts in default", weight: "watch", hits: defaults, rule: "Past maturity with an amount outstanding. The sweep marks it; nobody has to notice." },
        { title: "Defaults cured", weight: "note", hits: cures, rule: "A default paid off afterwards. Late payment clears it and stakes like any settlement — default is a state, not a verdict." },
        { title: "A debt handed on", weight: "watch", hits: handedOn, rule: "A contract taken over by another debtor. The row closes and a new one opens in the successor's name; the ledger holds that a handover and a plain default cost the community the same, and what moves is who carries it." },
        { title: "Underwriters stood in", weight: "note", hits: substitution, rule: "A contract's creditor changed. That is the subrogation leg of an insured default: the underwriter takes over the claim. The substitution leg opens new contracts instead, so this counts the first underwriter's piece and not the whole event." },
        { title: "Insurance lost", weight: "watch", hits: lostInsurance, rule: "A contract that was insured and no longer is. Insurance is decided at acceptance and can only fall." },
        { title: "Most of the credit in one pair of hands", weight: "watch", hits: concentration, rule: "One creditor owed more than two fifths of everything outstanding. No rule forbids it; their failure would be felt by everybody." },
        { title: "A wall of maturities", weight: "watch", hits: maturityWall, rule: "More than two fifths of what is owed falls due within a week — what the community has to find, all at once." },
        { title: "Owing with nothing behind it", weight: "note", hits: overExtended, rule: "A member owing money with no capacity left: further credit to them is uninsured, and the creditor carries it alone." },
      ],
    },
    {
      topic: "Shapes worth a second look",
      note: "None of these is an accusation. Each is a pattern that would look the same whether somebody meant it or not.",
      studies: [
        { title: "The same two, both ways", weight: "watch", hits: bothWays, rule: "Two people with contracts running in both directions, twice each way or more. A stake is the peak of what was repaid and never the sum, so a loop earns nothing — which is what makes trying it interesting." },
        { title: "Small round amounts, over and over", weight: "watch", hits: roundAndSmall, rule: "Three or more offers of round amounts under 50.00 to the same party: the shape of a record being made rather than a trade being done." },
        { title: "Wrote about records, then traded", weight: "watch", hits: solicited, rule: "Somebody wrote in public or in private about paperwork, documentation, an invoice or an arrangement, and made offers within the next three days. The words are matched by keyword and may be a refusal of exactly that; the connection is this rule's guess and nobody else's." },
        { title: "One person bringing in many", weight: "note", hits: seater, rule: "Three or more new rows seated by the same member's trades. Seats are a stock priced by a reservation, so a farm is bounded — but the shape is worth seeing." },
        { title: "Declines a great deal", weight: "note", hits: pressed, rule: "Five or more offers declined by the same person: somebody being pressed, somebody hard to please, or somebody with nothing to gain from what is on offer." },
        { title: "Borrows, never lends", weight: "note", hits: onlyBorrows, rule: "Debtor on three or more contracts and creditor on none. Selling earns standing; borrowing alone does not." },
      ],
    },
    {
      topic: "Whether the ledger is used at all",
      note: "The paper's thesis is conditional. This is the condition, measured.",
      studies: [
        { title: "Members never party to a contract", weight: "note", hits: untouched, rule: "On the ledger, and never once a debtor or a creditor." },
        { title: "Settling in money instead", weight: "watch", hits: settlingInCash, rule: "More cash payments than acts on the ledger. Clearing beats settling in currency only where enough of what a community buys is inside it." },
        { title: "Nobody ever says no", weight: "watch", hits: neverRefuses, rule: "Fewer than one refusal in twenty of what was put to somebody. A population that accepts everything is one whose agreement carries no information." },
        { title: "People who never acted", weight: "note", hits: silentPeople, rule: "Known to the run and never did a single thing — which may say more about the apparatus than about them." },
        { title: "Days lost to the apparatus", weight: "note", hits: lostDays, rule: "Days that produced nothing because a call failed, a limit was hit, or a life outgrew the model. Not the community's behaviour: ours." },
      ],
    },
    {
      topic: "The world they live in",
      note: "The shadow economy is drawn, not chosen. It is the pressure the ledger is answering.",
      studies: [
        { title: "Households with nothing left", weight: "watch", hits: underWater, rule: "No cash and bills unpaid. The ledger has no bankruptcy; this is where pressure shows." },
        { title: "Income cuts biting", weight: "note", hits: pressure, rule: "A quarter of households or more under an income cut — a correlated shock, drawn for everybody at once." },
        { title: "The economy in crisis", weight: "note", hits: crisis, rule: "The hidden regime reached crisis. Nobody in the community is told this; they see prices and their own income." },
      ],
    },
  ];
}
