<script>
  import { createEventDispatcher } from "svelte";
  import { shortName, initials, naming, outcomeText } from "./analytics.js";
  import { meaning, segments } from "./codes.js";
  import { hint } from "./hint.js";
  import Icon from "./Icon.svelte";
  export let day;
  export let run;
  const dispatch = createEventDispatcher();
  const who = (person) => shortName(run, person);
  $: named = naming(run);
  const outcome = (row, person) => outcomeText(run, row, person, named);
  const verbs = {
    offer: "Made an offer",
    sign: "Signed a contract",
    decline: "Declined an offer",
    pay_cash: "Made a cash payment",
    post: "Spoke on the square",
    message: "Sent a message",
    diary: "Wrote in their diary",
  };
  $: events = day.events.filter((e) => e.event !== "opened");
</script>

<div class="events">
  {#each events as e}
    {#if e.event === 'day'}
      <article class="event">
        <button class="event-person" on:click={() => dispatch('choose', e.person)}><span class="avatar" class:underwriter={day.members.some((m) => m.person === e.person && m.supply > 0)}>{initials(who(e.person))}</span><span><strong>{who(e.person)}</strong><small>{e.acts.length === 1 ? verbs[e.acts[0].act.act] || 'Took an action' : `${e.acts.length} recorded actions`} <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></small></span><Icon name="chevron" size={13} /></button>
        <div class="event-content">
          {#if !e.acts.length && !e.refused.length}<p class="quiet">Looked, and chose to do nothing.</p>{/if}
          {#each e.acts as a}
            <div class="act" class:diary={a.act.act === 'diary'}>
              {#if ['diary', 'post', 'message'].includes(a.act.act)}
                {#if e.acts.length > 1 || a.act.act === 'message'}<span class="act-label">{a.act.act === 'message' ? `To ${who(a.act.to)}` : a.act.act === 'diary' ? 'Diary' : 'On the square'} <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></span>{/if}
                <p class="quotation">“{a.act.text}”</p>
              {:else}
                <p>{named(a.act.describe) || a.act.act}</p><span class="outcome" class:rejected={['refused', 'rejected'].includes(a.result.result)}><span></span>{outcome(a, e.person)}</span>
              {/if}
            </div>
          {/each}
          {#each e.refused as a}<div class="act"><p>{named(a.act.describe)}</p><span class="outcome rejected"><span class="outcome-text">Refused · {#each segments(outcome(a, e.person)) as part}{#if part.code}<code class="code-hint" use:hint={meaning(part.code)}>{part.text}</code>{:else}{part.text}{/if}{/each}</span></span></div>{/each}
        </div>
      </article>
    {:else if e.event === 'silent'}
      <article class="event"><button class="event-person" on:click={() => dispatch('choose', e.person)}><span class="avatar">{initials(who(e.person))}</span><span><strong>{who(e.person)}</strong><small>Silent <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></small></span><Icon name="chevron" size={13} /></button><p class="event-detail">{e.reason}</p></article>
    {:else if e.event === 'card'}
      <article class="event system-event"><span class="event-symbol"><Icon name="people" size={16} /></span><div><button class="text-button" on:click={() => dispatch('choose', e.person)}>{e.name} joined <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></button><p>{e.card}</p><span class="muted">{e.tier} tier</span></div></article>
    {:else if e.event === 'instructions'}
      <article class="event system-event"><span class="event-symbol"><Icon name="activity" size={16} /></span><div><strong>Standing instructions <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></strong>{#each e.fired as f}<p><button class="text-button" on:click={() => dispatch('choose', f.person)}>{who(f.person)}</button>: {named(f.act.describe)} → {outcome(f, f.person)}</p>{/each}{#if !e.fired.length}<p>No instructions fired.</p>{/if}</div></article>
    {:else if e.event === 'violation'}
      <article class="event system-event"><span class="coral-text"><Icon name="shield" size={16} /></span><div><strong class="coral-text">An invariant failed</strong><p>{e.invariant}</p></div></article>
    {:else if e.event === 'ended'}
      <article class="event system-event"><Icon name="info" size={16} /><div><strong>The run ended</strong><p>{e.reason}</p></div></article>
    {:else if e.event === 'model_changed'}
      <article class="event system-event"><Icon name="info" size={16} /><div><strong>The model changed</strong><p>{e.from} → {e.to}. What follows is a different experiment.</p></div></article>
    {/if}
  {/each}
  {#if !events.length}<div class="empty-message">No recorded activity on this day.</div>{/if}
  {#if day.mail.length}<div class="private-messages"><div class="eyebrow">PRIVATE MESSAGES <span class="g" use:hint={"Generated by the model playing this person: one run's sample, never a measurement of how people behave."}>ⓖ</span></div>{#each day.mail as m}<p><button class="text-button" on:click={() => dispatch('choose', m.from)}>{who(m.from)}</button> → <button class="text-button" on:click={() => dispatch('choose', m.to)}>{who(m.to)}</button></p><blockquote>“{m.text}”</blockquote>{/each}</div>{/if}
</div>

<style>
  .events {
    padding: 0 20px;
    overflow-wrap: anywhere;
  }
  .event {
    padding: 18px 0 15px;
    border-bottom: 1px solid var(--line);
  }
  .event:last-child {
    border-bottom: 0;
  }
  .event-person {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 0;
    width: 100%;
    text-align: left;
    border: 0;
    background: none;
  }
  .event-person > span:nth-child(2) {
    flex: 1;
  }
  .event-person strong {
    display: block;
    font-size: 11px;
    font-weight: 500;
  }
  .event-person small {
    font-size: 9px;
    color: var(--muted);
    display: block;
    margin-top: 5px;
  }
  .event-person :global(svg) {
    color: var(--muted);
  }
  .event-content {
    padding-left: 43px;
  }
  .act {
    margin-top: 10px;
  }
  .act p {
    color: var(--secondary);
    line-height: 1.75;
    font-size: 10px;
  }
  .code-hint {
    font-family: var(--mono);
    border-bottom: 1px dotted currentColor;
  }
  /* One flex item, so the words stay a sentence rather than a row of items. */
  .outcome-text {
    min-width: 0;
  }
  .outcome {
    display: flex;
    gap: 5px;
    align-items: center;
    color: var(--mint);
    font-size: 9px;
    line-height: 1.7;
    margin-top: 5px;
  }
  .outcome > span:empty {
    width: 3px;
    height: 3px;
    border-radius: 50%;
    background: currentColor;
    flex-shrink: 0;
  }
  .outcome.rejected {
    color: var(--coral);
  }
  .act-label {
    font-size: 9px;
    color: var(--muted);
    display: block;
    margin-bottom: 4px;
  }
  .act .quotation {
    color: var(--secondary);
    border-left: 1px solid var(--line);
    padding-left: 9px;
    font-style: italic;
  }
  .quiet {
    color: var(--muted);
    margin-top: 10px;
    font-size: 10px;
  }
  .event-detail {
    font-size: 10px;
    color: var(--muted);
    padding-left: 43px;
    margin-top: 10px;
    line-height: 1.7;
  }
  .system-event {
    display: flex;
    gap: 12px;
    align-items: flex-start;
    font-size: 10px;
  }
  .system-event > :global(svg) {
    flex-shrink: 0;
    color: var(--muted);
  }
  .event-symbol {
    color: var(--gold);
  }
  .system-event p {
    margin-top: 8px;
    line-height: 1.7;
    color: var(--secondary);
  }
  .system-event strong {
    font-size: 11px;
    font-weight: 500;
  }
  .private-messages {
    padding: 18px 0;
  }
  .private-messages p {
    font-size: 10px;
    color: var(--muted);
    margin-top: 15px;
  }
  .private-messages blockquote {
    margin: 8px 0;
    font-size: 11px;
    line-height: 1.7;
    color: var(--secondary);
  }
  .private-messages .text-button {
    font-size: 10px;
  }
</style>
