/**
 * Background mode: the acceptance rule going on deciding while the app is not
 * in front of the member.
 *
 * **The engine is this page.** `autosign.ts` polls the pending pool over
 * `fetch` and signs with the seed held in this JavaScript context; no
 * signature crosses IPC. So "does the rule keep deciding" is exactly "does
 * this page keep running", and every platform answers it differently:
 *
 *   - **Android pauses the WebView the moment the app leaves the
 *     foreground.** `WryActivity.onPause()` — generated by wry, never ours to
 *     edit — calls `mWebView.onPause()`, whose contract is to pause the
 *     WebView's "extra processing … DOM, plugins, JavaScript". `MainActivity`
 *     re-resumes it while this mode is armed, and a foreground service
 *     (`edet-background`) keeps the process off the cached-process list and
 *     the app out of App Standby. Neither reaches past Doze: an unplugged,
 *     stationary device with the screen off has its network suspended for
 *     every app outside the battery-optimisation allowlist, foreground
 *     service or not. That is documented rather than fought
 *     (`openBatteryOptimisationSettings`), because a wallet that pretends to
 *     be awake is worse than one that says when it sleeps.
 *   - **The desktop ends the process when the window closes.** With this on,
 *     the close button hides the window to a tray icon instead, and the page
 *     goes on running behind it.
 *   - **A browser tab has neither**, so nothing is armed there and the store
 *     stays false: the rule decides while the tab is open, as it always did.
 *
 * What it never does is sign while the app is gone. A killed process, a
 * locked vault, a device that is off: none of them can be signed through, and
 * the copy beside the switch says so. When the vault locks under an armed
 * rule the member is told, because a rule that has silently stopped is the
 * one failure this mode could hide.
 */

import { get, writable } from 'svelte/store';
import { _ } from 'svelte-i18n';
import { invoke } from '@tauri-apps/api/core';
import {
    Importance,
    Visibility,
    createChannel,
    isPermissionGranted,
    requestPermission,
    sendNotification,
} from '@tauri-apps/plugin-notification';

import { formatNumber } from '../common/functions';
import { isTauri } from './api';
import { currentActorId, holdsSeed } from './actors';
import { memberName } from './display';
import { epochDate } from './epoch';
import { setPollInterval } from './node';
import { acceptancePolicy, type AcceptancePolicy } from './policy';
import { txSummary } from './txSummary';
import { isTauriAndroid, lockState, withTimeout, type LockState } from '../common/vault';

/** How often the pool is polled with the member watching. */
export const FOREGROUND_INTERVAL_MS = 1_500;
/**
 * And how often once the page is hidden. Nobody is reading the screen, so the
 * only thing the rate buys is how long a buyer waits for a signature; ten
 * seconds is the starting point the battery measurement moves, not a constant
 * anything else depends on.
 */
export const BACKGROUND_INTERVAL_MS = 10_000;

/**
 * How long any of these IPC calls may take before this device stops waiting.
 *
 * A hang is not an error and no `catch` sees one: an unanswered `invoke` would
 * leave `backgroundArmed` claiming nothing and this module's applied state
 * pinned to a transition that never completed. Every call here is a service
 * being started or a tray being built — none is slow — so a bound this
 * generous only ever catches a wedge.
 */
const IPC_TIMEOUT_MS = 5_000;

/**
 * **Two channels, because they are two different interruptions.**
 *
 * A payment signed in the member's name is a receipt: worth knowing, never
 * urgent, and somebody selling all day will want it silent. Something waiting
 * on a PERSON is the opposite — nothing moves until they act. On one channel a
 * member can only mute both or neither, and the one they would reach for is
 * the frequent one, which takes the other with it.
 *
 * The service's own channel is the Kotlin side's (`AcceptanceService`): it is
 * permanent and belongs to the process rather than to anything that happened.
 *
 * Android only. Everywhere else the id rides along on the notification and is
 * ignored, which is why only the creation is conditional.
 */
export const CHANNEL_PAYMENTS = 'edet-payments';
export const CHANNEL_WAITING = 'edet-waiting';

/**
 * Declare them, in the member's own language.
 *
 * Re-declared at every start rather than once: `createNotificationChannel` on
 * an existing id updates the NAME and the description, so a member who changes
 * the app's language sees the channels rename with it. What it cannot change
 * is the importance — Android hands that to the member the moment the channel
 * exists, which is the point of having them at all.
 */
async function ensureChannels(): Promise<void> {
    if (!isTauriAndroid()) return;
    const t = get(_);
    const declared = [
        {
            id: CHANNEL_PAYMENTS,
            name: t('background.channelPayments', { default: 'Signed by your rule' }),
            description: t('background.channelPaymentsDesc', {
                default: 'A purchase your acceptance rule signed while you were not looking.',
            }),
        },
        {
            id: CHANNEL_WAITING,
            name: t('background.channelWaiting', { default: 'Waiting for you' }),
            description: t('background.channelWaitingDesc', {
                default: 'A request or an approval that only you can decide.',
            }),
        },
    ];
    for (const channel of declared) {
        try {
            await createChannel({ ...channel, importance: Importance.Default, visibility: Visibility.Private });
        } catch (e) {
            // A device that will not take the channel still takes the
            // notification: it falls back to the plugin's own default.
            console.warn('notification channel', channel.id, e);
        }
    }
}

/**
 * Why this device is, or is not, deciding in the background.
 *
 *   armed  — the rule is on, this device holds the seed, the vault is open.
 *   off    — the member has not asked for it (or has turned the rule off).
 *   nokey  — no acting identity, or its seed is not on this device: there is
 *            nothing here that could sign.
 *   locked — a passphrase is set and has not been entered. The seed is in the
 *            vault and the vault is shut, so the rule cannot decide anything
 *            until the member unlocks it — which is worth saying out loud.
 */
export type ArmState = 'armed' | 'off' | 'nokey' | 'locked';

/**
 * The whole arming rule, as a function of what it reads — so the test states
 * it rather than driving four stores to state it.
 */
export function armState(
    policy: AcceptancePolicy,
    actor: number | null,
    lock: LockState,
    holds: (id: number) => boolean = holdsSeed,
): ArmState {
    if (!policy.auto || !policy.background) return 'off';
    if (actor === null || !holds(actor)) return 'nokey';
    if (lock === 'locked') return 'locked';
    return 'armed';
}

/**
 * Whether the platform is actually holding this app up right now — the
 * service running, or the tray icon present. Distinct from `armState`, which
 * is what the member asked for: this one is what the answer to that ask was.
 */
export const backgroundArmed = writable<boolean>(false);

/** Last state applied, so a store re-emission is not a second `arm` call. */
let applied: ArmState | null = null;

/**
 * The strings the platform itself shows: Android's service notification, and
 * the desktop tray's tooltip and menu.
 *
 * They travel with the arming call rather than living in Android string
 * resources or a Rust constant, because the member chose a language HERE and
 * a tray menu in English beside a translated app is the one part of the
 * client that did not listen.
 */
function labels(): { title: string; body: string; open: string; quit: string } {
    const t = get(_);
    return {
        title: t('background.serviceTitle', { default: 'Acceptance rule on' }),
        body: t('background.serviceBody', {
            default: 'Deciding requests in the background. Nothing signs once the app is closed.',
        }),
        open: t('background.trayOpen', { default: 'Open edet' }),
        quit: t('background.trayQuit', { default: 'Quit — stops deciding' }),
    };
}

/**
 * Ask for the notification permission, once, when the member turns this on.
 *
 * A foreground service's own notification is exempt from
 * `POST_NOTIFICATIONS`, so the service runs either way; what a refusal costs
 * is the "somebody bought something" notification, which is the whole point
 * of leaving the app running. So it is asked for here rather than at the
 * first payment, when the member is elsewhere and cannot answer.
 */
async function ensureNotificationPermission(): Promise<boolean> {
    try {
        if (await isPermissionGranted()) return true;
        return (await requestPermission()) === 'granted';
    } catch {
        return false;
    }
}

/**
 * Post one notification, and never let its failure reach the caller.
 *
 * The icon is named because the plugin's Android fallback is
 * `android.R.drawable.ic_dialog_info` — a stock system glyph, on a message
 * telling a member that credit was granted in their name. `ic_edet_notification`
 * is the mark, shipped by the `edet-background` module and merged into the
 * app's resources, and it is what the foreground service uses too, so a member
 * sees one icon for one app.
 *
 * **`largeBody` is what makes it expandable, and without it the sentence is
 * cut off with no way to see the rest.** The plugin sets `BigTextStyle` only
 * when that field is present; `body` alone is a single truncated line. What is
 * being truncated here is who bought what for how much — the whole content of
 * the message — so it carries the same text, and a member who taps it gets the
 * rest rather than a shrug. Every field but the title and body is ignored off
 * Android.
 */
async function notify(title: string, body: string, channelId: string): Promise<void> {
    if (!isTauri()) return;
    try {
        if (!(await isPermissionGranted())) return;
        sendNotification({
            title,
            body,
            largeBody: body,
            channelId,
            icon: 'ic_edet_notification',
            iconColor: '#7B1FA2',
        });
    } catch (e) {
        console.warn('notification failed', e);
    }
}

/**
 * Tell the member something, but only while they are not looking at the app.
 *
 * With edet in front, whatever this would say is already on a screen they can
 * see — the Requests list, the badge in the drawer — and a notification for
 * something visible is noise. Every notice in the client goes through here
 * (`lib/waiting.ts` is the other caller) so that rule is stated once.
 */
export async function notifyIfAway(title: string, body: string, channelId = CHANNEL_WAITING): Promise<void> {
    if (typeof document !== 'undefined' && document.visibilityState === 'visible') return;
    await notify(title, body, channelId);
}

/**
 * A payment landed while the member was not looking.
 *
 * Called on `signed` and on nothing else — a decline costs the member nothing
 * to read later, and the pool entry it refused is gone.
 */
export async function notifySigned(tx: Record<string, any>): Promise<void> {
    // Nothing in here may reach the caller: the acceptance engine does not
    // await this, so a throw would be an unhandled rejection over a decision
    // that has already been made and recorded.
    try {
        const t = get(_);
        const body = txSummary(tx, {
            t,
            nameOf: get(memberName),
            fmt: (n, d) => formatNumber(n, d ?? 2),
            dateOf: get(epochDate),
        });
        await notifyIfAway(t('background.signedTitle', { default: 'Signed for you' }), body, CHANNEL_PAYMENTS);
    } catch (e) {
        console.warn('notification failed', e);
    }
}

/**
 * Tell the platform what this device now wants, and record what it got.
 *
 * Every failure lands as "not armed": a service that would not start and a
 * tray that could not be created are both a device that will stop deciding
 * when it is put down, and the store the settings screen reads must say so.
 */
async function apply(state: ArmState): Promise<void> {
    if (state === applied) return;
    const previous = applied;
    applied = state;
    // The first pass at boot is a DISARM when the mode is off, and that is
    // deliberate: it costs one round trip and it leaves no room for a service
    // or a tray that outlived the page which asked for it to go on claiming a
    // rule this device is not running.

    if (!isTauri()) {
        backgroundArmed.set(false);
        return;
    }
    try {
        if (state === 'armed') {
            await ensureNotificationPermission();
            await withTimeout(invoke('background_arm', { labels: labels() }), IPC_TIMEOUT_MS, 'background_arm');
            backgroundArmed.set(true);
        } else {
            await withTimeout(invoke('background_disarm'), IPC_TIMEOUT_MS, 'background_disarm');
            backgroundArmed.set(false);
        }
    } catch (e) {
        backgroundArmed.set(false);
        console.warn('background mode', e);
    }
    // The one transition worth a notification: the member asked this device to
    // keep deciding, and it has stopped because the vault shut. Nothing else
    // would tell them — that is exactly the state in which they are not
    // looking at the app.
    if (state === 'locked' && previous === 'armed') {
        const t = get(_);
        await notify(
            t('background.lockedTitle', { default: 'Unlock to keep deciding' }),
            t('background.lockedBody', {
                default: 'Your acceptance rule is paused: open edet and enter your passphrase.',
            }),
            // The rule has stopped and only the member can restart it, which is
            // the waiting channel's whole subject.
            CHANNEL_WAITING,
        );
    }
}

/** Re-pace the poll for whether anybody is watching the screen. */
function onVisibility(): void {
    const hidden = typeof document !== 'undefined' && document.visibilityState === 'hidden';
    // Coming back to the front is the other moment the system bars may have
    // changed under the app — a rotation while it was away raises no `resize`
    // it was there to hear.
    if (!hidden) void applySystemInsets();
    // `setPollInterval` restarts the poll, which polls once immediately — so
    // coming back to the foreground refreshes at once rather than after the
    // background interval has run out.
    setPollInterval(hidden ? BACKGROUND_INTERVAL_MS : FOREGROUND_INTERVAL_MS);
}

/** The bars move with the screen, so the reserved room is re-read with it. */
function onResize(): void {
    void applySystemInsets();
}

let unsubscribers: Array<() => void> = [];
let listening = false;

/**
 * Start watching the three things arming depends on. Idempotent, and called
 * after `startPolling` so the visibility handler can only ever re-pace a poll
 * that is already running.
 */
export function startBackground(): void {
    if (unsubscribers.length > 0) return;
    const reapply = (): void => {
        void apply(armState(get(acceptancePolicy), get(currentActorId), get(lockState)));
    };
    unsubscribers = [
        acceptancePolicy.subscribe(reapply),
        currentActorId.subscribe(reapply),
        lockState.subscribe(reapply),
    ];
    if (typeof document !== 'undefined' && !listening) {
        document.addEventListener('visibilitychange', onVisibility);
        window.addEventListener('resize', onResize);
        listening = true;
    }
    void applySystemInsets();
    // Declared before anything can be posted to them; a notification naming a
    // channel that does not exist is dropped on Android O+.
    void ensureChannels();
}

export function stopBackground(): void {
    for (const u of unsubscribers) u();
    unsubscribers = [];
    if (listening && typeof document !== 'undefined') {
        document.removeEventListener('visibilitychange', onVisibility);
        window.removeEventListener('resize', onResize);
        listening = false;
    }
    void apply('off');
}

/** Test-only: forget what was last applied. */
export function resetBackgroundForTests(): void {
    applied = null;
    backgroundArmed.set(false);
}

/**
 * Reserve the room the platform's own chrome is taking.
 *
 * **`env(safe-area-inset-*)` is not enough, and it fails silently.** Measured
 * in the live WebView on a handset: the top inset reads 37 px and the
 * BOTTOM reads 0, because Android maps the safe area from the display cutout
 * and never from the navigation bar. So an edge-to-edge page puts its own
 * footer under the nav buttons — the acceptance rule's Save button was there —
 * and the stylesheet has no way to know. This asks the platform and publishes
 * the answer as `--edet-inset-*`, which the layout takes the `max()` of
 * against `env()` (`App.svelte`): where `env()` is right nothing is
 * double-counted, and where it is silent the layout is still correct.
 *
 * Called at boot and on every resize, because the bars move — a rotation, a
 * switch from three buttons to gestures, a keyboard.
 */
export async function applySystemInsets(): Promise<void> {
    if (!isTauri() || typeof document === 'undefined') return;
    try {
        const i = await withTimeout(
            invoke<{ top: number; bottom: number; left: number; right: number }>('background_system_insets'),
            IPC_TIMEOUT_MS,
            'background_system_insets',
        );
        const style = document.documentElement.style;
        for (const side of ['top', 'bottom', 'left', 'right'] as const) {
            const px = i?.[side];
            if (typeof px === 'number' && Number.isFinite(px) && px >= 0) {
                style.setProperty(`--edet-inset-${side}`, `${px}px`);
            }
        }
    } catch (e) {
        // The layout falls back to `env()`, which is what it had before.
        console.warn('system insets', e);
    }
}

/**
 * Does the member still have something to grant?
 *
 * `true` only on Android, and only while edet is subject to battery
 * optimisation: a member who has already exempted it has nothing left to do,
 * and briefing them again about a setting they have already changed is how a
 * prompt becomes something people dismiss without reading. Off Android, and
 * below the API where Doze exists, there is nothing to grant at all.
 *
 * **An unreadable answer counts as "still needed".** It is not "already
 * exempt": the cost of one redundant screen is a tap, and the cost of a
 * briefing that never appears is a wallet that quietly stops deciding when the
 * phone is put down.
 */
export async function needsBatteryExemption(): Promise<boolean> {
    if (!isTauriAndroid()) return false;
    try {
        return await withTimeout(
            invoke<boolean>('background_battery_optimised'),
            IPC_TIMEOUT_MS,
            'background_battery_optimised',
        );
    } catch (e) {
        console.warn('battery optimisation state', e);
        return true;
    }
}

/**
 * Open Android's battery-optimisation settings, where a member can exempt
 * edet from Doze.
 *
 * Nothing in this app acquires a wake lock or otherwise stays awake past what
 * the OS allows; the exemption is the member's to grant, on their own device,
 * in the OS's own screen. Off Android there is nothing to open.
 */
export async function openBatteryOptimisationSettings(): Promise<void> {
    if (!isTauriAndroid()) return;
    try {
        await withTimeout(
            invoke('background_open_battery_settings'),
            IPC_TIMEOUT_MS,
            'background_open_battery_settings',
        );
    } catch (e) {
        console.warn('battery settings', e);
    }
}
