/**
 * The inclusion-proof verifier, cross-pinned two ways.
 *
 * First against fixtures generated by the normative implementation itself.
 * The `RUST_*` constants below are real proofs emitted by
 * `cargo run -p edet-state --example proof_fixture` over five founding
 * underwriters, captured in the node's wire shape — REGENERATE them from that
 * example rather than editing them by hand. They were once hand-copied, and
 * when `Section::ALL` grew a `pending` section under both sides this test kept
 * passing: the reimplementation and its oracle had drifted together, which is
 * the one failure a cross-pin exists to be immune to.
 *
 * Second against a prover written independently in this file: the verifier
 * derives each fold's structure from `(index, leaf_count)` and the
 * section's fixed position, so building trees here and mutating one field
 * at a time checks that every deviation from the committed shape — not
 * just a wrong hash — is rejected.
 */
import { afterEach, describe, expect, it, vi } from 'vitest';
import { sha256 } from '@noble/hashes/sha2';

import { parseProof, verifyProof, verifyProofJson, SECTIONS } from '../proof';
import { fetchProof } from '../api';
import { bytesToHex } from '../crypto';

// ------------------------------------------------- an independent prover ----

const SECTION_NAMES = ['members', 'contracts', 'proposals', 'validators', 'stakes', 'replay', 'ledger'];
// Kept as its own map, not derived from the order above: position and tag do
// not agree, and a prover that derived one from the other would model the
// verifier's own mistake instead of checking it. Mirrors `SECTION_TAG` in
// ../proof.
const SECTION_TAGS: Record<string, number> = {
    members: 0,
    contracts: 1,
    proposals: 2,
    validators: 3,
    stakes: 5,
    replay: 6,
    ledger: 4,
};

function enc(s: string): Uint8Array {
    return new TextEncoder().encode(s);
}

function cat(...parts: Uint8Array[]): Uint8Array {
    const out = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
    let at = 0;
    for (const p of parts) {
        out.set(p, at);
        at += p.length;
    }
    return out;
}

function be64(n: number): Uint8Array {
    const out = new Uint8Array(8);
    new DataView(out.buffer).setBigUint64(0, BigInt(n));
    return out;
}

/** `leaf_hash` per `root.rs`: 0x00 ‖ "edet-leaf-v3" ‖ salt ‖ tag ‖ be64(index) ‖ framed key ‖ framed value. */
function leaf(salt: Uint8Array, tag: number, index: number, key: Uint8Array, value: Uint8Array): Uint8Array {
    return sha256(
        cat(
            Uint8Array.of(0x00),
            enc('edet-leaf-v3'),
            salt,
            Uint8Array.of(tag),
            be64(index),
            be64(key.length),
            key,
            be64(value.length),
            value,
        ),
    );
}

function inner(l: Uint8Array, r: Uint8Array): Uint8Array {
    return sha256(cat(Uint8Array.of(0x01), l, r));
}

/**
 * `section_hash` per `root.rs`: 0x02 ‖ "edet-section-v1" ‖ tag ‖ be64(count)
 * ‖ leaves root. The section's leaf count is bound here and nowhere else, so
 * a prover that skipped it would agree with a verifier that skipped it too.
 */
function sectionRoot(tag: number, count: number, leavesRoot: Uint8Array): Uint8Array {
    return sha256(cat(Uint8Array.of(0x02), enc('edet-section-v1'), Uint8Array.of(tag), be64(count), leavesRoot));
}

/**
 * Build a promotion tree level by level — the prover-side shape, mirroring
 * `fold_level` in `root.rs` rather than the verifier's `fold_path`, so the
 * two sides arrive at the structure independently. Collects the sibling
 * consumed at each level by the node tracked from leaf `track`; a promoted
 * node contributes none.
 */
function merkle(leaves: Uint8Array[], track: number): { root: Uint8Array; path: Uint8Array[] } {
    let level = leaves.slice();
    let t = track;
    const path: Uint8Array[] = [];
    while (level.length > 1) {
        const up: Uint8Array[] = [];
        for (let i = 0; 2 * i < level.length; i++) {
            const l = level[2 * i];
            if (2 * i + 1 < level.length) {
                const r = level[2 * i + 1];
                up.push(inner(l, r));
                if (t === 2 * i) {
                    path.push(r);
                    t = -i - 1; // mark resolved for this level
                } else if (t === 2 * i + 1) {
                    path.push(l);
                    t = -i - 1;
                }
            } else {
                up.push(l); // odd level: the last node is promoted
                if (t === 2 * i) {
                    t = -i - 1;
                }
            }
        }
        level = up;
        t = -t - 1;
    }
    return { root: level[0], path };
}

/** The wire shape the node serves. */
interface Wire {
    section: string;
    index: number;
    leaf_count: number;
    key: string;
    value: string;
    leaf_salt: string;
    path: string[];
    section_path: string[];
}

/**
 * An honest fixture: a section of `leafCount` distinct leaves, the other six
 * section roots arbitrary (the verifier never inspects them), the top tree
 * folded over all seven in the fixed order. Salts are arbitrary 32-byte
 * values — the verifier recomputes the leaf from whatever salt the proof
 * disclosed, so any salt the tree was actually built with is honest.
 */
function fixture(section: string, leafCount: number, index: number, key?: Uint8Array): { root: string; proof: Wire } {
    // Position in the top tree and tag byte inside the leaf are two different
    // numbers, and this prover has to model both or it stops being independent
    // of the thing it checks.
    const pos = SECTION_NAMES.indexOf(section);
    const tag = SECTION_TAGS[section];
    const keys: Uint8Array[] = [];
    const values: Uint8Array[] = [];
    const salts: Uint8Array[] = [];
    const leaves: Uint8Array[] = [];
    for (let i = 0; i < leafCount; i++) {
        keys.push(key !== undefined && i === index ? key : be64(i));
        values.push(sha256(enc(`value-${section}-${i}`)));
        salts.push(sha256(enc(`salt-${section}-${i}`)));
        leaves.push(leaf(salts[i], tag, i, keys[i], values[i]));
    }
    const section_tree = merkle(leaves, index);
    const sectionRoots = SECTION_NAMES.map((name, i) =>
        i === pos ? sectionRoot(tag, leafCount, section_tree.root) : sha256(enc(`other-root-${name}`)),
    );
    const top = merkle(sectionRoots, pos);
    return {
        root: bytesToHex(top.root),
        proof: {
            section,
            index,
            leaf_count: leafCount,
            key: bytesToHex(keys[index]),
            value: bytesToHex(values[index]),
            leaf_salt: bytesToHex(salts[index]),
            path: section_tree.path.map(bytesToHex),
            section_path: top.path.map(bytesToHex),
        },
    };
}

// --------------------------------- fixtures from the Rust implementation ----

const RUST_ROOT = '630afe60f946c5e96db22de7be3e815753e2541419dc70ddc978b314e7ec8d25';

const RUST_MEMBER_2_OF_5 = {
    section: 'members',
    index: 2,
    leaf_count: 5,
    key: '0000000000000002',
    value: '02000000000000000100000000000000030303030303030303030303030303030303030303030303030303030303030300000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    leaf_salt: '777242b699f5997858dceb216c686d01c0d766a21942a58d10fef968f9b5742b',
    path: [
        '1fd5e0d5b807ad9c1852a8c25d41e223efcbc3400a9c43863bc6139cd22a3dc0',
        '5721fb9ae5a172afbc72ed292174108ee1fe03e5b001c126686c0045d94f0e5c',
        'd5320e98dc224178c4141de39e2f1dfb50ee2b98167cf1543b0e7f37b93d93f8',
    ],
    section_path: [
        'de93f7e4fc9b745907e8ddc11f92a9345f0fa5fa733df3c5a38a64cbb6787fa8',
        '5db2e061c36fed6c6c67cb93a71ef23ba6819d806158915058a75bc32aec8371',
        '7ec121c0b7ee97981bf90e9bead6bebdc32bf7298a1989090882bc53d2cd50bf',
    ],
};

const RUST_MEMBER_4_OF_5 = {
    section: 'members',
    index: 4,
    leaf_count: 5,
    key: '0000000000000004',
    value: '04000000000000000100000000000000050505050505050505050505050505050505050505050505050505050505050500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
    leaf_salt: '64859d28950c270716d14f68f046b6477f72c54eb17b784946d04b625555398c',
    path: [
        'bfb5d7a40f950482a8e5f07c1bdbf48f39e5c63549185cdb23f394c91ea461a0',
    ],
    section_path: [
        'de93f7e4fc9b745907e8ddc11f92a9345f0fa5fa733df3c5a38a64cbb6787fa8',
        '5db2e061c36fed6c6c67cb93a71ef23ba6819d806158915058a75bc32aec8371',
        '7ec121c0b7ee97981bf90e9bead6bebdc32bf7298a1989090882bc53d2cd50bf',
    ],
};

const RUST_STAKES_2_OF_5 = {
    section: 'stakes',
    index: 2,
    leaf_count: 5,
    key: '0000000000000002',
    value: '0000000000000000',
    leaf_salt: '7a936ee8dd50a26ad9b6da6e3e8becf4db34bd0c7adb42507e89fe6526f5064f',
    path: [
        '3e1afc918970688f7764a6c0b58e968086f7c8f1eb1ce86301e0d0d200c195bd',
        'aada8f0acb31159449977d24f369e0b0a7d4f6d302f9d5a70218ac461af368d3',
        'c71df998a8f0b8c779c79f6c3306f3dcacbeed01dc89d788f23f69d10eeccd22',
    ],
    section_path: [
        'c1e03898f895fcd7ed113069ce5fa9d1ecabaf63af63579775c1032e4539b719',
        'c3a8bf68c65cd85a5361046767e90be852200e67a278f3297ca24b42d7b7174b',
        'f3fc5e0621f531b31816b627e20d5efd7b6f75f058694692335b2e746a2af221',
    ],
};

const RUST_LEDGER = {
    section: 'ledger',
    index: 0,
    leaf_count: 1,
    key: '',
    value: '0000000000408f407b14ae47e17a843f000000000000e83f000000000000e03f555555555555e53f00000000000000000000000000888e407b14ae47e17a943f7b14ae47e17a943f0000000000d0764020000000010000000000000003000000000000001e000000000000005a00000000000000000000000000e03f0100000000000000000000000000000000000000000000000005000000000000000000000000000000000000000000000000000000000000000800000000000000656465742d64657600000000000000000500000000000000000000000000000090d0030000000000010000000000000090d0030000000000020000000000000090d0030000000000030000000000000090d0030000000000040000000000000090d0030000000000000000000000000000000000000000000000000000000000',
    leaf_salt: '6cf719bd76079dd663134ca6ae33b308964d31f833a5bbbaffdae2ad15b1ac33',
    path: [
    ],
    section_path: [
        '464704ef0c06935219d2492731a216ac9cba4e1733d0e05511d2f45d41d5f672',
        'f3fc5e0621f531b31816b627e20d5efd7b6f75f058694692335b2e746a2af221',
    ],
};


// --------------------------------------------------------------- the pin ----

describe('proofs produced by the Rust implementation', () => {
    it('verify against the root it computed', () => {
        expect(verifyProofJson(RUST_ROOT, RUST_MEMBER_2_OF_5)).toBe(true);
        expect(verifyProofJson(RUST_ROOT, RUST_MEMBER_4_OF_5)).toBe(true);
        expect(verifyProofJson(RUST_ROOT, RUST_STAKES_2_OF_5)).toBe(true);
        expect(verifyProofJson(RUST_ROOT, RUST_LEDGER)).toBe(true);
    });

    it('do not verify against a root with one bit flipped', () => {
        const flipped = RUST_ROOT.slice(0, -1) + (RUST_ROOT.endsWith('6') ? '7' : '6');
        expect(verifyProofJson(flipped, RUST_MEMBER_2_OF_5)).toBe(false);
    });

    it('do not verify once the committed value is touched', () => {
        const tampered = { ...RUST_MEMBER_2_OF_5, value: '00' + RUST_MEMBER_2_OF_5.value.slice(2) };
        expect(verifyProofJson(RUST_ROOT, tampered)).toBe(false);
    });
});

// ---------------------------------------------------------- honest proofs ----

describe('honest proofs', () => {
    it('verify for every leaf at every size, including the promoting ones', () => {
        // 1 = no path at all; 2 = one pair; 3, 5, 7 = odd levels that must
        // promote; 4, 8 = fully paired; 6, 9 = promotion above level 0.
        for (const n of [1, 2, 3, 4, 5, 6, 7, 8, 9]) {
            for (let i = 0; i < n; i++) {
                const { root, proof } = fixture('members', n, i);
                expect(verifyProofJson(root, proof), `size ${n}, index ${i}`).toBe(true);
            }
        }
    });

    it('verify in every section, whose position in the top tree the name determines', () => {
        for (const section of SECTION_NAMES) {
            const { root, proof } = fixture(section, 3, 1);
            expect(verifyProofJson(root, proof), section).toBe(true);
        }
    });

    it('verify with an empty key, which the ledger leaf actually has', () => {
        const { root, proof } = fixture('ledger', 1, 0, new Uint8Array(0));
        expect(proof.key).toBe('');
        expect(verifyProofJson(root, proof)).toBe(true);
    });

    it('accept the section name case-insensitively', () => {
        const { root, proof } = fixture('members', 2, 0);
        expect(verifyProofJson(root, { ...proof, section: 'Members' })).toBe(true);
        expect(verifyProofJson(root, { ...proof, section: 'MEMBERS' })).toBe(true);
    });

    it('decode through parseProof into the canonical shape', () => {
        const { proof } = fixture('members', 2, 1);
        const parsed = parseProof({ ...proof, section: 'Members' });
        expect(parsed).not.toBeNull();
        expect(parsed?.section).toBe('members');
        expect(parsed?.index).toBe(1);
        expect(parsed?.leafCount).toBe(2);
        expect(bytesToHex(parsed!.value)).toBe(proof.value);
    });
});

// -------------------------------------------------------------- mutations ----

describe('a mutated proof does not verify', () => {
    // Size 7 at index 4: three levels, a sibling consumed on each, and both
    // halves of the proof populated.
    const good = fixture('members', 7, 4);

    it('fixture sanity: the honest proof verifies and both paths are populated', () => {
        expect(verifyProofJson(good.root, good.proof)).toBe(true);
        expect(good.proof.path.length).toBe(3);
        expect(good.proof.section_path.length).toBe(3);
    });

    it('rejects a tampered value', () => {
        const p = { ...good.proof, value: good.proof.value + '00' };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects a tampered key', () => {
        const p = { ...good.proof, key: bytesToHex(be64(5)) };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects a tampered leaf salt', () => {
        const p = { ...good.proof, leaf_salt: '00'.repeat(32) };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects another in-range index — the position is committed in the leaf', () => {
        const p = { ...good.proof, index: 3 };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects an index outside the tree', () => {
        expect(verifyProofJson(good.root, { ...good.proof, index: 7 })).toBe(false);
        expect(verifyProofJson(good.root, { ...good.proof, index: 100 })).toBe(false);
    });

    it('rejects another leaf count — the tree size is committed at the section root', () => {
        const p = { ...good.proof, leaf_count: 8 };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects a resized section that folds to the very same leaves root', () => {
        // The one case the leaf hash cannot catch, and the reason the count
        // is bound at the section root: which side each sibling sits on is a
        // function of the INDEX alone, and the presence pattern for index 0
        // is identical at three leaves and at four. Same leaf, same siblings,
        // same leaves root — only the section's committed count differs.
        //
        // Mutation that bites: drop `count` from `sectionHash`.
        const three = fixture('members', 3, 0);
        expect(verifyProofJson(three.root, three.proof)).toBe(true);
        expect(three.proof.path.length).toBe(2);
        expect(verifyProofJson(three.root, { ...three.proof, leaf_count: 4 })).toBe(false);
    });

    it('rejects the promotion alias: the same siblings under a smaller claimed tree', () => {
        // The last leaf of a 3-leaf tree folds through the identical
        // sibling sequence as leaf 1 of a 2-leaf tree; the index inside the
        // leaf hash and the count inside the section root each tell the two
        // claims apart on their own.
        const promoted = fixture('members', 3, 2);
        expect(verifyProofJson(promoted.root, promoted.proof)).toBe(true);
        const alias = { ...promoted.proof, index: 1, leaf_count: 2 };
        expect(verifyProofJson(promoted.root, alias)).toBe(false);
    });

    it('rejects a dropped sibling', () => {
        const p = { ...good.proof, path: good.proof.path.slice(0, -1) };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects an appended sibling — leftovers are a forgery, not padding', () => {
        const p = { ...good.proof, path: [...good.proof.path, '11'.repeat(32)] };
        expect(verifyProofJson(good.root, p)).toBe(false);
        const q = { ...good.proof, section_path: [...good.proof.section_path, '11'.repeat(32)] };
        expect(verifyProofJson(good.root, q)).toBe(false);
    });

    it('rejects reordered siblings', () => {
        const swapped = [good.proof.path[1], good.proof.path[0], good.proof.path[2]];
        expect(verifyProofJson(good.root, { ...good.proof, path: swapped })).toBe(false);
    });

    it('rejects a sibling moved across the path/section_path boundary, either way', () => {
        const down = {
            ...good.proof,
            path: [...good.proof.path, good.proof.section_path[0]],
            section_path: good.proof.section_path.slice(1),
        };
        expect(verifyProofJson(good.root, down)).toBe(false);

        const up = {
            ...good.proof,
            path: good.proof.path.slice(0, -1),
            section_path: [good.proof.path[good.proof.path.length - 1], ...good.proof.section_path],
        };
        expect(verifyProofJson(good.root, up)).toBe(false);

        const flattened = {
            ...good.proof,
            path: [...good.proof.path, ...good.proof.section_path],
            section_path: [],
        };
        expect(verifyProofJson(good.root, flattened)).toBe(false);
    });

    it('rejects the same bytes relabelled to another section', () => {
        // The section tag is inside the leaf hash and the top-tree position
        // is derived from the name, so a relabel breaks both folds.
        const p = { ...good.proof, section: 'contracts' };
        expect(verifyProofJson(good.root, p)).toBe(false);
    });

    it('rejects a valid proof against the wrong root', () => {
        expect(verifyProofJson('00'.repeat(32), good.proof)).toBe(false);
        // A ledger with different CONTENTS, not merely a proof of a different
        // leaf within the same one: `fixture` derives every key and value from
        // the section and the leaf position, so two fixtures differing only in
        // which index they prove build the identical tree and share a root —
        // and this assertion would pass vacuously against it. The roots are
        // compared first so it cannot quietly become vacuous again.
        const other = fixture('members', 8, 3);
        expect(other.root).not.toBe(good.root);
        expect(verifyProofJson(other.root, good.proof)).toBe(false);
    });
});

// -------------------------------------------------------- malformed input ----

describe('malformed input is null/false, never a throw', () => {
    const good = fixture('members', 3, 1);

    it('rejects non-objects', () => {
        for (const bad of [null, undefined, 42, 'proof', true, [], [good.proof]]) {
            expect(parseProof(bad)).toBeNull();
            expect(verifyProofJson(good.root, bad)).toBe(false);
        }
    });

    it('rejects a proof missing any field', () => {
        for (const field of Object.keys(good.proof)) {
            const p: Record<string, unknown> = { ...good.proof };
            delete p[field];
            expect(parseProof(p), `missing ${field}`).toBeNull();
        }
    });

    it('rejects an unknown section rather than defaulting it', () => {
        expect(parseProof({ ...good.proof, section: 'wallets' })).toBeNull();
        expect(parseProof({ ...good.proof, section: '' })).toBeNull();
        expect(parseProof({ ...good.proof, section: 0 })).toBeNull();
    });

    it('rejects a negative, fractional or non-numeric position', () => {
        for (const bad of [-1, 1.5, NaN, Infinity, '1', 2 ** 53]) {
            expect(parseProof({ ...good.proof, index: bad }), `index ${String(bad)}`).toBeNull();
            expect(parseProof({ ...good.proof, leaf_count: bad }), `leaf_count ${String(bad)}`).toBeNull();
        }
    });

    it('rejects bad hex anywhere', () => {
        expect(parseProof({ ...good.proof, key: 'zz' })).toBeNull();
        expect(parseProof({ ...good.proof, value: 'abc' })).toBeNull();
        expect(parseProof({ ...good.proof, leaf_salt: good.proof.leaf_salt.slice(2) + 'g0' })).toBeNull();
        expect(parseProof({ ...good.proof, path: [good.proof.path[0].slice(0, 63) + 'x'] })).toBeNull();
    });

    it('rejects a hash that is not exactly 32 bytes', () => {
        expect(parseProof({ ...good.proof, leaf_salt: '00'.repeat(31) })).toBeNull();
        expect(parseProof({ ...good.proof, leaf_salt: '00'.repeat(33) })).toBeNull();
        expect(parseProof({ ...good.proof, path: ['00'.repeat(31)] })).toBeNull();
        expect(parseProof({ ...good.proof, section_path: ['00'.repeat(33)] })).toBeNull();
    });

    it('rejects paths that are not arrays of strings', () => {
        expect(parseProof({ ...good.proof, path: 'ab'.repeat(32) })).toBeNull();
        expect(parseProof({ ...good.proof, path: [42] })).toBeNull();
        expect(parseProof({ ...good.proof, section_path: {} })).toBeNull();
    });

    it('rejects a malformed expected root', () => {
        expect(verifyProofJson('', good.proof)).toBe(false);
        expect(verifyProofJson('xyz', good.proof)).toBe(false);
        expect(verifyProofJson('00'.repeat(31), good.proof)).toBe(false);
        expect(verifyProofJson('00'.repeat(33), good.proof)).toBe(false);
    });

    it('re-checks structure on a hand-constructed proof, not only off the wire', () => {
        const parsed = parseProof(good.proof)!;
        expect(verifyProof(good.root, parsed)).toBe(true);
        expect(verifyProof(good.root, { ...parsed, leafSalt: parsed.leafSalt.slice(0, 31) })).toBe(false);
        expect(verifyProof(good.root, { ...parsed, index: -1 })).toBe(false);
        expect(verifyProof(good.root, { ...parsed, path: [parsed.path[0].slice(0, 31)] })).toBe(false);
    });
});

// The exported section list is itself part of the format: the node's
// `Section::ALL` order, which fixes every section's top-tree position.
describe('the section order', () => {
    it('is the seven sections in the order root.rs fixes', () => {
        expect([...SECTIONS]).toEqual(SECTION_NAMES);
    });
});


// ------------------------------------------------- the client's own gate ----

describe('fetchProof discards what does not verify', () => {
    const base = 'http://node.test';

    afterEach(() => {
        vi.unstubAllGlobals();
    });

    function respond(body: unknown) {
        vi.stubGlobal(
            'fetch',
            vi.fn(async () => ({ ok: true, status: 200, json: async () => body })),
        );
    }

    it('returns a proof that verifies against the root it arrived with', async () => {
        respond({ height: 9, app_hash: RUST_ROOT, proof: RUST_MEMBER_2_OF_5 });
        const r = await fetchProof(base, 'member', 2);
        expect(r?.proof).not.toBeNull();
        expect(r?.height).toBe(9);
    });

    // The whole value of this read is that the client checks. A node that
    // serves a proof for a DIFFERENT ledger — buggy, or lying — must not have
    // its word rendered as evidence.
    it('discards a proof that does not verify against the served root', async () => {
        respond({ height: 9, app_hash: '00'.repeat(32), proof: RUST_MEMBER_2_OF_5 });
        const r = await fetchProof(base, 'member', 2);
        expect(r?.proof).toBeNull();
    });

    it('discards a tampered leaf even when the node reports success', async () => {
        respond({
            height: 9,
            app_hash: RUST_ROOT,
            proof: { ...RUST_MEMBER_2_OF_5, value: RUST_MEMBER_2_OF_5.value.replace(/^02/, '03') },
        });
        expect((await fetchProof(base, 'member', 2))?.proof).toBeNull();
    });

    it('treats a refusal as no evidence rather than an error', async () => {
        respond({ error: 'forbidden: a proof discloses the whole record' });
        expect(await fetchProof(base, 'member', 2)).toBeNull();
    });
});
