#!/bin/bash

# patch-signing.sh — Write the complete app/build.gradle.kts that includes
# Android release signing, reading credentials from environment variables.
#
# Because src-tauri/gen/android/ is .gitignored and re-generated by
# `tauri android init`, this script is the single source of truth for
# what build.gradle.kts should look like.  It always writes the file
# from scratch, so it is unconditionally idempotent — safe to run any
# number of times without risk of double-patching.
#
# Signing is CONDITIONAL on environment variables:
#
#   • ANDROID_STORE_FILE set  → signed build  (CI path)
#   • ANDROID_STORE_FILE unset → unsigned build (local dev path)
#
# Required environment variables (signed build only)
# ─────────────────────────────────────────────────────────────────────
#   ANDROID_STORE_FILE        absolute path to the .jks keystore on disk
#   ANDROID_STORE_PASSWORD    keystore password
#   ANDROID_KEY_ALIAS         key alias inside the keystore
#   ANDROID_KEY_PASSWORD      key password
#
# Usage (CI — called by .github/workflows/android-release.yml):
#   ANDROID_STORE_FILE=/tmp/edet-release.jks \
#   ANDROID_STORE_PASSWORD=... \
#   ANDROID_KEY_ALIAS=edet \
#   ANDROID_KEY_PASSWORD=... \
#   bash scripts/patch-signing.sh
#
# Usage (local — unsigned build, no env vars needed):
#   bash scripts/patch-signing.sh

set -euo pipefail

ANDROID_DIR="src-tauri/gen/android"
GRADLE_FILE="$ANDROID_DIR/app/build.gradle.kts"

if [[ ! -d "$ANDROID_DIR" ]]; then
    echo "Error: $ANDROID_DIR not found. Run 'tauri android init' first."
    exit 1
fi

# ── Decide whether to include signing config ──────────────────────────────────

SIGNING="false"
if [[ -n "${ANDROID_STORE_FILE:-}" ]]; then
    : "${ANDROID_STORE_PASSWORD:?ANDROID_STORE_PASSWORD must be set when ANDROID_STORE_FILE is set}"
    : "${ANDROID_KEY_ALIAS:?ANDROID_KEY_ALIAS must be set when ANDROID_STORE_FILE is set}"
    : "${ANDROID_KEY_PASSWORD:?ANDROID_KEY_PASSWORD must be set when ANDROID_STORE_FILE is set}"
    SIGNING="true"
    echo "Signing: ENABLED (keystore=$ANDROID_STORE_FILE, alias=$ANDROID_KEY_ALIAS)"
else
    echo "Signing: DISABLED (ANDROID_STORE_FILE not set — unsigned build)"
fi

# ── Write build.gradle.kts from scratch ──────────────────────────────────────
# This matches the file that `tauri android init` generates, plus the
# optional signingConfigs block and signingConfig reference in release.

{
cat <<'HEADER'
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("rust")
}

val tauriProperties = Properties().apply {
    val propFile = file("tauri.properties")
    if (propFile.exists()) {
        propFile.inputStream().use { load(it) }
    }
}

android {
    compileSdk = 36
    namespace = "org.edet"
    defaultConfig {
        manifestPlaceholders["usesCleartextTraffic"] = "true"
        applicationId = "org.edet"
        minSdk = 26
        targetSdk = 36
        versionCode = tauriProperties.getProperty("tauri.android.versionCode", "1").toInt()
        versionName = tauriProperties.getProperty("tauri.android.versionName", "1.0")
    }
HEADER

if [[ "$SIGNING" == "true" ]]; then
cat <<'SIGNING_BLOCK'
    signingConfigs {
        // Written by scripts/patch-signing.sh.
        // Credentials are read from environment variables set by the CI workflow.
        create("release") {
            storeFile = file(System.getenv("ANDROID_STORE_FILE") ?: "")
            storePassword = System.getenv("ANDROID_STORE_PASSWORD") ?: ""
            keyAlias = System.getenv("ANDROID_KEY_ALIAS") ?: ""
            keyPassword = System.getenv("ANDROID_KEY_PASSWORD") ?: ""
        }
    }
SIGNING_BLOCK
fi

cat <<'BUILDTYPES_START'
    buildTypes {
        getByName("debug") {
            manifestPlaceholders["usesCleartextTraffic"] = "true"
            isDebuggable = true
            isJniDebuggable = true
            isMinifyEnabled = false
            packaging {                jniLibs.keepDebugSymbols.add("*/arm64-v8a/*.so")
                jniLibs.keepDebugSymbols.add("*/armeabi-v7a/*.so")
                jniLibs.keepDebugSymbols.add("*/x86_64/*.so")
            }
        }
        getByName("release") {
BUILDTYPES_START

if [[ "$SIGNING" == "true" ]]; then
cat <<'SIGNING_REF'
            signingConfig = signingConfigs.getByName("release")
SIGNING_REF
fi

cat <<'FOOTER'
            isMinifyEnabled = false
            proguardFiles(
                *fileTree(".") { include("**/*.pro") }
                    .plus(getDefaultProguardFile("proguard-android-optimize.txt"))
                    .toList().toTypedArray()
            )
        }
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    buildFeatures {
        buildConfig = true
    }
}

rust {
    rootDirRel = "../../../"
}

dependencies {
    implementation("androidx.webkit:webkit:1.14.0")
    implementation("androidx.appcompat:appcompat:1.7.1")
    implementation("androidx.activity:activity-ktx:1.10.1")
    implementation("com.google.android.material:material:1.12.0")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.4")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.0")
}

apply(from = "tauri.build.gradle.kts")
FOOTER

} > "$GRADLE_FILE"

echo "Written: $GRADLE_FILE"
