#!/usr/bin/env python3
r"""Generate the paper's seed-turnover table from the probe that measures it.

`paper/sections/110-adoption.tex` tells a founding community to size its seed
against peak simultaneous insured credit rather than annual volume, and prints
a table of how much trade one seed insures in a year at each settlement term.
A table of figures that nothing in the tree produces is not a measurement --
it is a paragraph with numerals in it, and the two that were there when this
script was written cited a settlement term the ledger refuses outright
(anything below `params.min_maturity_epochs`, which no `ParamKey` reaches).

So the table is GENERATED, by the same shape `proof-fixture.py` uses for the
client's proof fixtures: run `cargo run -p edet-state --example seed_table`,
which drives the real transition function through a year of trade per term,
and write its output to `paper/sections/generated-seed-table.tex`, which
`110-adoption.tex` `\input`s.

Two modes, matching the other paper gate:
  * default: regenerate the file in place (`just seed-table`).
  * `--check`: regenerate to memory, byte-diff, exit 1 on drift
    (`just seed-table-check`, in `ci`).

Stdlib-only, so a gate that runs on every push cannot break on a dependency of
its own.
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_TEX = REPO_ROOT / "paper" / "sections" / "generated-seed-table.tex"

HEADER = """% Auto-generated by scripts/seed-table.py from
% crates/state/examples/seed_table.rs, which measures it against the real
% transition function. Do not hand-edit: change the probe and run
% `just seed-table`. `just seed-table-check` (part of `just ci`) fails the
% build if this file drifts from the measurement it was generated from.
"""


def measured() -> str:
    """The table, straight from the probe."""
    out = subprocess.run(
        ["cargo", "run", "--quiet", "-p", "edet-state", "--example", "seed_table"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    if out.returncode != 0:
        sys.stderr.write(out.stderr)
        raise SystemExit(f"seed-table: the probe failed (exit {out.returncode})")
    return HEADER + out.stdout.rstrip("\n") + "\n"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="regenerate to memory and byte-diff against the committed file "
        "instead of writing it; exit 1 on drift",
    )
    args = parser.parse_args(argv)

    content = measured()

    if not args.check:
        GENERATED_TEX.write_text(content, encoding="utf-8")
        print(f"seed-table: wrote {GENERATED_TEX}")
        return 0

    if not GENERATED_TEX.exists():
        print(
            f"seed-table: {GENERATED_TEX} does not exist -- run `just seed-table` "
            "and commit it.",
            file=sys.stderr,
        )
        return 1
    committed = GENERATED_TEX.read_text(encoding="utf-8")
    if committed == content:
        print(f"seed-table: {GENERATED_TEX} is up to date.")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            committed.splitlines(keepends=True),
            content.splitlines(keepends=True),
            fromfile=f"{GENERATED_TEX} (committed)",
            tofile=f"{GENERATED_TEX} (regenerated from seed_table.rs)",
        )
    )
    print(
        "\nseed-table: the paper's seed-turnover table no longer matches what "
        "the probe measures -- run `just seed-table` and commit the result.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
