//! Lair seed import for deterministic mnemonic recovery.
//!
//! The `tauri-plugin-holochain` runtime owns lair's lifecycle (spawn,
//! init, passphrase, shutdown). What it does *not* do is plant a
//! caller-supplied seed under a specific tag — which is what edet's
//! onboarding wizard needs so the resulting `AgentPubKey` is
//! deterministic across devices from the same mnemonic.
//!
//! This module implements the X25519 crypto_box envelope that
//! `lair_keystore_api::LairClient::import_seed` expects on the wire, and
//! exposes two helpers on top of an already-connected `LairClient`:
//!
//! - `import_ed25519_seed(client, seed)` — import a 32-byte raw seed
//!   under `LAIR_SEED_TAG` and return the resulting ed25519 pubkey
//! - `new_random_seed(client)` — create a fresh CSPRNG seed under the
//!   same tag, for users who decline a mnemonic
//!
//! Type-layout notes (lair_keystore_api 0.6.3):
//!   - `X25519PubKey = BinDataSized<32>` is a tuple struct with
//!     `pub Arc<[u8; 32]>` inside (so `.0` dereferences to the array).
//!   - `SeedInfo.ed25519_pub_key: Ed25519PubKey = BinDataSized<32>` so
//!     `.0` also extracts the 32 raw bytes.
//!
//! The logic here was extracted verbatim from the pre-plugin
//! `src-tauri/src/lair.rs::import_ed25519_seed` and given a free
//! function signature that takes `&LairClient` directly. The only
//! behavioural change is the caller: the plugin hands us its
//! `LairClient` via `conductor_handle.keystore().lair_client()`
//! instead of us wrapping lair in our own subprocess manager.

use anyhow::{bail, Context, Result};
use lair_keystore_api::prelude::{BinDataSized, SeedInfo, LairClient, X25519PubKey};

/// Name of the lair seed tag edet's agent key lives under. All UI
/// callers agree on this constant; must not change across versions
/// without a migration path.
pub const LAIR_SEED_TAG: &str = "edet-agent-v1";

/// The tag under which tauri-plugin-holochain stores the device seed.
/// This entry is always present after plugin initialisation and its
/// X25519 pubkey is the correct `recipient` for `LairClient::import_seed`.
const DEVICE_SEED_TAG: &str = "DEVICE_SEED";

/// Import a 32-byte ed25519 seed under `LAIR_SEED_TAG` and return the
/// resulting public key as a 32-byte ed25519 pubkey. Callers need to
/// wrap this into a Holochain `AgentPubKey` (39 bytes with the DHT
/// coordinate suffix) themselves.
///
/// ## Wire protocol
///
/// `LairClient::import_seed` uses a **seed-to-seed** NaCl crypto_box:
///
/// - **recipient** must be the X25519 pubkey of an *existing lair seed
///   entry*. Lair looks it up by that key and uses the corresponding
///   X25519 secret key to decrypt the payload. The `get_enc_ctx_key()`
///   session key is NOT an entry — using it causes "Query returned no
///   rows". We use `DEVICE_SEED` (always present after plugin init) as
///   the recipient instead.
/// - **sender** is an ephemeral X25519 keypair generated by us; only
///   the public half is sent on the wire.
///
/// If a seed already exists under `LAIR_SEED_TAG` (e.g. from a previous
/// partial run after conductor data was wiped), `import_seed` will error.
/// In that case we fall back to `get_entry` to return the existing pubkey.
pub async fn import_ed25519_seed(client: &LairClient, seed: [u8; 32]) -> Result<[u8; 32]> {
    use crypto_box::{
        aead::{Aead, AeadCore, OsRng},
        PublicKey, SalsaBox, SecretKey,
    };
    use std::sync::Arc as StdArc;

    // Retrieve the DEVICE_SEED entry to get its X25519 pubkey. This seed
    // is created by tauri-plugin-holochain at every first launch and is
    // always present when we reach this point.
    let device_entry = client
        .get_entry(DEVICE_SEED_TAG.into())
        .await
        .context("lair get_entry(DEVICE_SEED) failed — plugin may not have initialised")?;

    let recipient_x25519: [u8; 32] = match &device_entry {
        lair_keystore_api::prelude::LairEntryInfo::Seed { seed_info, .. }
        | lair_keystore_api::prelude::LairEntryInfo::DeepLockedSeed { seed_info, .. } => {
            *seed_info.x25519_pub_key.0
        }
        _ => anyhow::bail!("DEVICE_SEED entry is not a seed — unexpected lair state"),
    };

    // Generate an ephemeral X25519 keypair. The public half goes on the
    // wire; the secret half is used to build the crypto_box and then dropped.
    let sender_secret = SecretKey::generate(&mut OsRng);
    let sender_public_bytes: [u8; 32] = sender_secret.public_key().as_bytes().to_owned();

    let recipient_pub = PublicKey::from(recipient_x25519);

    // Encrypt the raw seed.
    let nonce = SalsaBox::generate_nonce(&mut OsRng);
    let boxed = SalsaBox::new(&recipient_pub, &sender_secret);
    let ciphertext = boxed
        .encrypt(&nonce, seed.as_slice())
        .map_err(|e| anyhow::anyhow!("crypto_box encrypt failed: {e}"))?;

    let mut nonce_bytes = [0u8; 24];
    nonce_bytes.copy_from_slice(nonce.as_slice());

    let sender_pub_lair: X25519PubKey = BinDataSized(StdArc::new(sender_public_bytes));
    let recipient_pub_lair: X25519PubKey = BinDataSized(StdArc::new(recipient_x25519));

    match client
        .import_seed(
            sender_pub_lair,
            recipient_pub_lair,
            None,
            nonce_bytes,
            ciphertext.into(),
            LAIR_SEED_TAG.into(),
            false,
        )
        .await
    {
        Ok(info) => Ok(*info.ed25519_pub_key.0),
        Err(e) => {
            // Tag already exists (lair persisted across a conductor wipe).
            // Return the pubkey of the existing entry.
            let entry = client
                .get_entry(LAIR_SEED_TAG.into())
                .await
                .context(format!("lair import_seed failed ({e}), get_entry also failed"))?;
            match entry {
                lair_keystore_api::prelude::LairEntryInfo::Seed { seed_info, .. }
                | lair_keystore_api::prelude::LairEntryInfo::DeepLockedSeed {
                    seed_info, ..
                } => Ok(*seed_info.ed25519_pub_key.0),
                _ => anyhow::bail!(
                    "lair import_seed failed ({e}) and existing entry is not a seed"
                ),
            }
        }
    }
}

/// Create a fresh random ed25519 seed under `LAIR_SEED_TAG` and return
/// its public key. Used for the "create new identity" path where the
/// user has declined to provide a deterministic mnemonic.
///
/// Note: the plugin auto-creates a seed under its own `DEVICE_SEED`
/// tag at launch time; we intentionally use our own `edet-agent-v1`
/// tag so onboarding/recovery stays under our control.
pub async fn new_random_seed(client: &LairClient) -> Result<[u8; 32]> {
    let info: SeedInfo = client
        .new_seed(LAIR_SEED_TAG.into(), None, false)
        .await
        .context("lair new_seed failed")?;
    Ok(*info.ed25519_pub_key.0)
}

/// Guard: make sure the caller is passing 32 bytes exactly. Consumers
/// (e.g. `commands::import_lair_seed`) should call this before
/// building the `[u8; 32]` fixed-size array.
#[allow(dead_code)]
pub fn validate_seed_len(bytes: &[u8]) -> Result<()> {
    if bytes.len() != 32 {
        bail!("seed must be 32 bytes, got {}", bytes.len());
    }
    Ok(())
}
