/**
 * The client's own signing digest, pinned to the node's.
 *
 * **This is what lets the wallet stop signing whatever a node hands it.** Until
 * a wallet that fetched the payload from `/tx/digest` and signed the reply —
 * or co-signed a pending entry by signing `entry.digest`, a hex string the same
 * node served, with nothing checking that it corresponded to the `entry.tx`
 * shown on screen — would let a node the member had been talked into adding
 * under `custom` answer with the digest of a different envelope and collect a
 * valid signature over it.
 *
 * Computing it here means a second implementation of a canonical encoding, and
 * two implementations drift. So the vectors below are GENERATED by the
 * normative one — `cargo run -p edet-node --features serve --example
 * tx_digest_fixture` — and `just tx-digest-check` fails on any drift, the same
 * shape as `proof-fixture-check`. A cross-pin whose oracle is hand-copied is
 * pinned to whatever was last pasted.
 */

import { describe, expect, it } from 'vitest';

import type { Tx } from '../api';
import { toHex, txDigestLocal, TxEncodeError } from '../txdigest';

// --------------------------------- fixtures from the Rust implementation ----

const RUST_CHAIN_ID = 'edet-fixture-chain';

const RUST_TX_DIGESTS = [
    {
        name: 'register_guardians',
        tx: {"RegisterGuardians":{"member":7,"guardians":[3,1,2],"threshold":2,"veto_window_epochs":30}},
        nonce: [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20100,
        digest: 'b419829a9d8a0ee25c6bb248acc21a5287bd642b44f11ffe6c93e03941f06abc',
    },
    {
        name: 'rotate_request',
        tx: {"RotateRequest":{"member":7,"new_keys":[[161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161,161],[162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162,162]]}},
        nonce: [2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20101,
        digest: '694168055349ffb62f412c5eeb2d91aaaf468949e6709d404aed9be0934116f7',
    },
    {
        name: 'rotate_veto',
        tx: {"RotateVeto":{"member":7}},
        nonce: [3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20102,
        digest: '6d87ffa81f95496bbee047948b1bdf58502845218b77081472b07fd568a371f5',
    },
    {
        name: 'rotate_finalize',
        tx: {"RotateFinalize":{"member":7}},
        nonce: [4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20103,
        digest: '5455653a2591462e253a4a2fedd50529556516b7b0db9eacdbfa3652ca006c03',
    },
    {
        name: 'set_consensus_key',
        tx: {"SetConsensusKey":{"member":7,"key":[199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199,199]}},
        nonce: [5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20104,
        digest: 'bdd974f801c4d076c6dd47d839ad09cb94cbfe4c701b6b847abb0684dbdc1be7',
    },
    {
        name: 'set_consensus_key_none',
        tx: {"SetConsensusKey":{"member":7,"key":null}},
        nonce: [6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20105,
        digest: '3701652efc48c0d521d489fcaa71038b18876425aaf6d0ebe233a2caad85e758',
    },
    {
        name: 'exit',
        tx: {"Exit":{"member":7}},
        nonce: [7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20106,
        digest: '5e8208c2d32f2c7007b9d6fde94fbe2b6ee5983202a3cae122052f83eb1adb51',
    },
    {
        name: 'list_beneficiaries',
        tx: {"ListBeneficiaries":{"supporter":7,"entries":[[3,0.25],[9,0.75]]}},
        nonce: [8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20107,
        digest: '622aa08371d4db0f1ced60783d2885bdfbe920ca4742f8b332b4375d4ad1c6fd',
    },
    {
        name: 'approve_supporter',
        tx: {"ApproveSupporter":{"beneficiary":7,"supporter":3,"approved":true}},
        nonce: [9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20108,
        digest: '3e64945fae560b538bf6a1ecb239aba55fc07e4c98f0d7be5c133d941a931e3c',
    },
    {
        name: 'sale_member',
        tx: {"Sale":{"seller":{"Member":7},"buyer":{"Member":3},"amount":1234.56,"maturity_epochs":45}},
        nonce: [10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20109,
        digest: '21f2efdedfbd4ec9b65d0e80e4f0968aff194ede699444f838ac6be8f26de993',
    },
    {
        name: 'sale_by_key',
        tx: {"Sale":{"seller":{"Member":7},"buyer":{"Key":[179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179,179]},"amount":0.07,"maturity_epochs":30}},
        nonce: [11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20110,
        digest: '85a83db3edb4bb650cfb9353c14fa99253118ffa7c217b9ccb90504deb99ecff',
    },
    {
        name: 'declare_supply',
        tx: {"DeclareSupply":{"member":7,"supply":2499.99}},
        nonce: [12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20111,
        digest: 'fb8deb90af440112209f67f0a39e0f338da924d0491324354bb2f74a3dd8db3e',
    },
    {
        name: 'accept_no_arb',
        tx: {"Accept":{"debtor":{"Member":3},"creditor":{"Member":7},"amount":987.65,"maturity_epochs":30,"arb":null}},
        nonce: [13, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20112,
        digest: 'b6198f85c8f6ccfc83a606a62c1735d0ed0ed30e4c4ac1e30e4bbb3804cd9ad2',
    },
    {
        name: 'accept_with_arb',
        tx: {"Accept":{"debtor":{"Key":[212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212,212]},"creditor":{"Member":7},"amount":42.42,"maturity_epochs":90,"arb":{"arbiters":[2,5,9],"quorum":2,"window_epochs":60,"award_cap":500.5}}},
        nonce: [14, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20113,
        digest: 'f049d2b775413123229e8d8edbb4d5a053f6cd6b9d7013c0b81deb9023229374',
    },
    {
        name: 'transfer',
        tx: {"Transfer":{"contract":12,"new_debtor":3}},
        nonce: [15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20114,
        digest: 'ae0ea6b209b6e2300932740e38128f4852c68b5d00d3c799c8aea01f5c82d7d1',
    },
    {
        name: 'settle',
        tx: {"Settle":{"contract":12,"amount":33.33}},
        nonce: [16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20115,
        digest: '8eb6e15f2bd7b79ea8f70246f1350474a463c9b647025e7d0bd91644b6486b99',
    },
    {
        name: 'extend',
        tx: {"Extend":{"contract":12,"new_maturity_epoch":20001}},
        nonce: [17, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20116,
        digest: '8a329f22080846b20aed262020707c8b7cba9b70c6ad294280cca948116ef322',
    },
    {
        name: 'mark_expired',
        tx: {"MarkExpired":{"contract":12}},
        nonce: [18, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20117,
        digest: 'b62f7bf7df33f950651862788e8c2002bf53de52450e3d00ef47a4ffe6d6fd5b',
    },
    {
        name: 'cure',
        tx: {"Cure":{"contract":12,"amount":7.77}},
        nonce: [19, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20118,
        digest: '9ae9a9ccd71b0d72563ba251fcc2b040657a70deb88e5afbaa95ecb6416092c9',
    },
    {
        name: 'arb_attest',
        tx: {"ArbAttest":{"contract":12,"arbiter":5,"amount":250.25}},
        nonce: [20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20119,
        digest: '085007072e973dbe6c128cddaee7506de7157544b00f34838a285e3d47ee09fb',
    },
    {
        name: 'propose_param_change',
        tx: {"Propose":{"author":7,"kind":{"ParamChange":{"key":"StakeDecay","value":980.0}}}},
        nonce: [21, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20120,
        digest: '1938ba7eda4f6a4c15a24e5054a909116b0f8b6caaea64751d4abda7a1b025f7',
    },
    {
        name: 'propose_param_change_horizon',
        tx: {"Propose":{"author":7,"kind":{"ParamChange":{"key":"InsuredHorizon","value":180.0}}}},
        nonce: [22, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20121,
        digest: '78cff109a0ce4f4d95ed6924efdb64a18a8b5f663a16d06346624c4ef58a01c0',
    },
    {
        name: 'propose_redenominate',
        tx: {"Propose":{"author":7,"kind":{"Redenominate":{"num":3,"den":2}}}},
        nonce: [23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20122,
        digest: 'f97068dc4871314e50a3bc23cd90a8530279e45c1ef9f98e5b991a7972371724',
    },
    {
        name: 'propose_suspend',
        tx: {"Propose":{"author":7,"kind":{"Suspend":{"member":3}}}},
        nonce: [24, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20123,
        digest: '79129ffa3e3d4796bb177bd88bac41bfc889d324a8ffafd079911db42035477b',
    },
    {
        name: 'propose_unsuspend',
        tx: {"Propose":{"author":7,"kind":{"Unsuspend":{"member":3}}}},
        nonce: [25, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20124,
        digest: '0a25f4fc18e194397bdfce2a0ad7f2082f1cf533a50bf125b884612ce0c89319',
    },
    {
        name: 'propose_validator_power',
        tx: {"Propose":{"author":7,"kind":{"ValidatorPower":{"member":3,"power":1}}}},
        nonce: [26, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20125,
        digest: '806c527c13d3a00d912954ac66c339a95beb8084cd11d19866421b3a138ec7d5',
    },
    {
        name: 'propose_seed_amendment',
        tx: {"Propose":{"author":7,"kind":{"SeedAmendment":{"amount":100.0}}}},
        nonce: [27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20126,
        digest: '6ae79c6dab21b615d77f7b0a6dff14b42a50cdf63c387d12b35ed5c71607d8cd',
    },
    {
        name: 'assent',
        tx: {"Assent":{"member":7,"proposal":4}},
        nonce: [28, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20127,
        digest: '1c914d71bc21df2285f9a60c3e87ad1fb5cff5504f47b0b2ff8f55c3d9830f12',
    },
    {
        name: 'forfeit_bonds',
        tx: {"ForfeitBonds":{"member":3}},
        nonce: [29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        not_after_epoch: 20128,
        digest: '1e05500b7c160340a3e5ef765d8f72b25fb29f2ee8a0c303d7d2513b7e490176',
    },
];


// ---------------------------------------------------------------- the pin ----

interface Vector {
    name: string;
    tx: Tx;
    nonce: number[];
    not_after_epoch: number;
    digest: string;
}

describe('the digest this device signs', () => {
    it('matches the node on every transaction in the alphabet', () => {
        for (const v of RUST_TX_DIGESTS as Vector[]) {
            expect(toHex(txDigestLocal(RUST_CHAIN_ID, v.tx, v.nonce, v.not_after_epoch)), v.name).toBe(v.digest);
        }
    });

    /** Every variant, so a new transaction cannot arrive unpinned. */
    it('covers the whole alphabet', () => {
        const names = new Set((RUST_TX_DIGESTS as Vector[]).map((v) => Object.keys(v.tx)[0]));
        expect(names.size).toBe(20);
    });

    /**
     * The chain id is length-prefixed into the preimage, and this is why:
     * without the prefix, one chain id followed by a payload can be spelled as
     * a different chain id followed by a different payload.
     */
    it('binds the signature to one chain', () => {
        const v = (RUST_TX_DIGESTS as Vector[])[0];
        const other = toHex(txDigestLocal(RUST_CHAIN_ID + 'x', v.tx, v.nonce, v.not_after_epoch));
        expect(other).not.toBe(v.digest);
    });

    /** And to one envelope: the nonce and the window are both covered. */
    it('binds the signature to one envelope', () => {
        const v = (RUST_TX_DIGESTS as Vector[])[0];
        const nonce = [...v.nonce];
        nonce[0] ^= 1;
        expect(toHex(txDigestLocal(RUST_CHAIN_ID, v.tx, nonce, v.not_after_epoch))).not.toBe(v.digest);
        expect(toHex(txDigestLocal(RUST_CHAIN_ID, v.tx, v.nonce, v.not_after_epoch + 1))).not.toBe(v.digest);
    });

    /**
     * **A panel is a SET, so the order a member clicked in is not part of it.**
     *
     * `ArbTerms.arbiters` is a `BTreeSet<MemberId>` on the ledger, so its
     * encoding is ascending — and the generated vectors cannot catch a client
     * that forgot that, because `serde_json` serialises the set already
     * sorted, so the fixture arrives in the order the encoder wants. Measured:
     * deleting the sort in `txdigest.ts` leaves every vector above green. This
     * is the probe that goes red for it.
     */
    it('orders an arbitration panel the way the ledger does, not the way it was typed', () => {
        const v = (RUST_TX_DIGESTS as Vector[]).find((x) => x.name === 'accept_with_arb')!;
        const accept = (v.tx as Extract<Tx, { Accept: unknown }>).Accept;
        const shuffled: Tx = {
            Accept: { ...accept, arb: { ...accept.arb!, arbiters: [...accept.arb!.arbiters].reverse() } },
        };
        expect(accept.arb!.arbiters.length, 'the fixture needs a panel to reorder').toBeGreaterThan(1);
        expect(toHex(txDigestLocal(RUST_CHAIN_ID, shuffled, v.nonce, v.not_after_epoch))).toBe(v.digest);
    });

    /**
     * **It refuses rather than falling back.** A transaction this encoder
     * cannot represent is one this device must not sign — and asking the node
     * for the digest instead is precisely the hole being closed, so there is
     * no such path to take.
     */
    it('refuses what it cannot encode exactly', () => {
        const unknown = { NotATransaction: { member: 1 } } as unknown as Tx;
        expect(() => txDigestLocal('c', unknown, new Array(16).fill(0), 1)).toThrow(TxEncodeError);
        const huge = { Exit: { member: Number.MAX_SAFE_INTEGER + 2 } } as Tx;
        expect(() => txDigestLocal('c', huge, new Array(16).fill(0), 1)).toThrow(TxEncodeError);
        const shortNonce = { Exit: { member: 1 } } as Tx;
        expect(() => txDigestLocal('c', shortNonce, [1, 2, 3], 1)).toThrow(TxEncodeError);
    });
});
